// Generated by cookbooks/_shared/ontology/gen_init_cypher.py
// DO NOT EDIT BY HAND — run `uv run python -m cookbooks._shared.ontology.gen_all`

// --- Uniqueness constraints ---
CREATE CONSTRAINT account_id_unique IF NOT EXISTS FOR (n:Account) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT statement_id_unique IF NOT EXISTS FOR (n:Statement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT transaction_id_unique IF NOT EXISTS FOR (n:Transaction) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT merchant_id_unique IF NOT EXISTS FOR (n:Merchant) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT category_id_unique IF NOT EXISTS FOR (n:Category) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT subscription_id_unique IF NOT EXISTS FOR (n:Subscription) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT memo_id_unique IF NOT EXISTS FOR (n:Memo) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT decision_id_unique IF NOT EXISTS FOR (n:Decision) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT annotation_id_unique IF NOT EXISTS FOR (n:Annotation) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT budget_id_unique IF NOT EXISTS FOR (n:Budget) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT recommendation_id_unique IF NOT EXISTS FOR (n:Recommendation) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT concept_review_id_unique IF NOT EXISTS FOR (n:ConceptReview) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT goal_id_unique IF NOT EXISTS FOR (n:Goal) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT net_worth_snapshot_id_unique IF NOT EXISTS FOR (n:NetWorthSnapshot) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT concept_id_unique IF NOT EXISTS FOR (n:Concept) REQUIRE n.id IS UNIQUE;

// --- Vector indexes ---
CREATE VECTOR INDEX transaction_clean_description_vec IF NOT EXISTS
FOR (n:Transaction) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 384,
  `vector.similarity_function`: 'cosine'
} };

CREATE VECTOR INDEX merchant_canonical_name_vec IF NOT EXISTS
FOR (n:Merchant) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 384,
  `vector.similarity_function`: 'cosine'
} };

CREATE VECTOR INDEX memo_text_vec IF NOT EXISTS
FOR (n:Memo) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 384,
  `vector.similarity_function`: 'cosine'
} };

CREATE VECTOR INDEX concept_name_vec IF NOT EXISTS
FOR (n:Concept) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 384,
  `vector.similarity_function`: 'cosine'
} };

// --- Full-text indexes ---
CREATE FULLTEXT INDEX merchant_fulltext IF NOT EXISTS
FOR (n:Merchant) ON EACH [n.canonical_name, n.aliases];

CREATE FULLTEXT INDEX concept_fulltext IF NOT EXISTS
FOR (n:Concept) ON EACH [n.name, n.description];

// --- Schema meta singleton ---
MERGE (m:Meta {id: 'schema'}) SET
  m.schema_version = 1,
  m.embedding_model = 'sentence-transformers/all-MiniLM-L6-v2',
  m.embedding_dim = 384;
