# Generated by cookbooks/_shared/ontology/gen_pydantic.py
# DO NOT EDIT BY HAND — run `uv run python -m cookbooks._shared.ontology.gen_all`
"""Auto-generated Pydantic models from the ontology.

These are the runtime validation surface for every write to Postgres
and Neo4j. Re-generate after any ontology edit.
"""
from __future__ import annotations

from pydantic import BaseModel


class Account(BaseModel):
    """A bank or credit-card account. ID shape: ``account::<sha256-of-number>``."""
    id: str

class Statement(BaseModel):
    """One source PDF for a billing/statement period. ID shape: ``statement::<sha256-of-pdf>``."""
    id: str

class Transaction(BaseModel):
    """One ledger row; projected from Postgres at compile time. ID shape: ``tx::<statement-id>::<row>``."""
    id: str
    clean_description: str
    embedding: list[float] | None = None

class Merchant(BaseModel):
    """Canonical merchant entity with surface-form aliases. ID shape: ``merchant::<canonical-slug>``."""
    id: str
    canonical_name: str
    embedding: list[float] | None = None
    aliases: list[str] = []

class Category(BaseModel):
    """Hierarchical spending category. ID shape: ``category::<slug>``."""
    id: str

class Subscription(BaseModel):
    """Detected recurring payment to a merchant. Wiki page IDs use sub_<merchant-slug>; the id_template below is the canonical Neo4j node ID shape introduced by the upgrade. ID shape: ``subscription::<merchant-id>::<cadence>``."""
    id: str

class Memo(BaseModel):
    """Monthly analyst-produced summary; content lives in wiki/memos/. ID shape: ``memo::<period>``."""
    id: str
    text: str
    embedding: list[float] | None = None

class Decision(BaseModel):
    """Audited record of an Action invocation; content lives in wiki/decisions/. ID shape: ``decision::<uuid>``."""
    id: str

class Annotation(BaseModel):
    """Manual user note attached to a transaction. ID shape: ``annotation::<uuid>``."""
    id: str

class Budget(BaseModel):
    """A monthly or annual spending target for a Category or Merchant. ID shape: ``budget::<scope>::<period>``."""
    id: str

class Recommendation(BaseModel):
    """An actionable suggestion from the advisor cookbook. ID shape: ``recommendation::<uuid>``."""
    id: str

class ConceptReview(BaseModel):
    """A queued question for the user to resolve manually. ID shape: ``concept_review::<uuid>``."""
    id: str

class Goal(BaseModel):
    """A target dollar amount to reach by a deadline; underpins plan-mode advice. ID shape: ``goal::<slug>``."""
    id: str

class NetWorthSnapshot(BaseModel):
    """Multi-account total position at a specific period boundary. ID shape: ``networth::<period>``."""
    id: str

class Concept(BaseModel):
    """Derived semantic concept ("subscription bloat", etc.) — populated in Tier 3. ID shape: ``concept::<slug>``."""
    id: str
    name: str
    embedding: list[float] | None = None
    description: str = ""
