"""Generates `cookbooks/_shared/models/_generated.py` from the ontology.

Emits one Pydantic v2 BaseModel per ObjectType with:
  - `id: str` (always; documented in the docstring with id_template)
  - the `embedding_field` (typed as `str`) if declared
  - `embedding: list[float] | None = None` if `embedding_field` is set
  - `description: str = ""` carrying the ontology description as a docstring

These models are the runtime validation surface for ingestion and the
compile step — every write to Postgres / Neo4j passes through them.

Output is deterministic. Run via gen_all.
"""
from __future__ import annotations

from pathlib import Path

from cookbooks._shared.ontology.loader import ObjectType, load_ontology

# parents[3]: cookbooks/_shared/ontology/gen_pydantic.py → repo root.
# Output lives at cookbooks/_shared/models/_generated.py.
OUTPUT_PATH = (
    Path(__file__).resolve().parents[3]
    / "cookbooks" / "_shared" / "models" / "_generated.py"
)


_HEADER = """\
# Generated by cookbooks/_shared/ontology/gen_pydantic.py
# DO NOT EDIT BY HAND — run `uv run python -m cookbooks._shared.ontology.gen_all`
\"\"\"Auto-generated Pydantic models from the ontology.

These are the runtime validation surface for every write to Postgres
and Neo4j. Re-generate after any ontology edit.
\"\"\"
from __future__ import annotations

from pydantic import BaseModel
"""


def _class_for(ot: ObjectType) -> str:
    lines = [f"class {ot.id}(BaseModel):"]
    docstring_parts = []
    if ot.description:
        docstring_parts.append(ot.description)
    if ot.id_template:
        docstring_parts.append(f"ID shape: ``{ot.id_template}``.")
    if docstring_parts:
        lines.append(f'    """{ " ".join(docstring_parts) }"""')

    lines.append("    id: str")
    if ot.embedding_field:
        lines.append(f"    {ot.embedding_field}: str")
        lines.append("    embedding: list[float] | None = None")
    for field in ot.text_search_fields:
        if field == ot.embedding_field:
            continue  # already declared above
        # Text search fields default to list[str] for aliases-like, str otherwise.
        if field.endswith("es") or field.endswith("s"):
            lines.append(f"    {field}: list[str] = []")
        else:
            lines.append(f'    {field}: str = ""')
    return "\n".join(lines)


def generate_pydantic() -> str:
    ont = load_ontology()
    parts = [_HEADER, ""]
    for ot in ont.object_types:
        parts.append(_class_for(ot))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def write_pydantic(path: Path = OUTPUT_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_pydantic(), encoding="utf-8")


def main() -> None:
    write_pydantic()
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
