"""Generates `db/neo4j/init.cypher` from the ontology.

Emits, in order:

  1. Uniqueness constraints on `id` for every ObjectType
  2. Vector indexes for every ObjectType that declares `embedding_field`
  3. Full-text indexes for every ObjectType that declares `text_search_fields`
  4. A singleton `(:Meta {id:'schema'})` node with version + embedding metadata

The output is **deterministic** — ObjectTypes are emitted in the order
they appear in the YAML, formatting is fixed, no timestamps. The
consistency CI test depends on this.

Run via:

    uv run python -m cookbooks._shared.ontology.gen_init_cypher

Or, more commonly, via the bundled `gen_all`:

    uv run python -m cookbooks._shared.ontology.gen_all
"""
from __future__ import annotations

from pathlib import Path

from cookbooks._shared.ontology._naming import (
    object_id_to_constraint_name,
    object_id_to_fulltext_index_name,
    object_id_to_label,
    object_id_to_vector_index_name,
)
from cookbooks._shared.ontology.loader import ObjectType, Ontology, load_ontology

OUTPUT_PATH = Path(__file__).resolve().parents[3] / "db" / "neo4j" / "init.cypher"


def _constraint_line(ot: ObjectType) -> str:
    label = object_id_to_label(ot.id)
    name = object_id_to_constraint_name(ot.id)
    return (
        f"CREATE CONSTRAINT {name} IF NOT EXISTS "
        f"FOR (n:{label}) REQUIRE n.id IS UNIQUE;"
    )


def _vector_index_lines(ot: ObjectType, meta_dim: int) -> list[str]:
    if not ot.embedding_field:
        return []
    label = object_id_to_label(ot.id)
    name = object_id_to_vector_index_name(ot.id, ot.embedding_field)
    dim = ot.embedding_dim or meta_dim
    return [
        f"CREATE VECTOR INDEX {name} IF NOT EXISTS",
        f"FOR (n:{label}) ON (n.embedding)",
        "OPTIONS { indexConfig: {",
        f"  `vector.dimensions`: {dim},",
        "  `vector.similarity_function`: 'cosine'",
        "} };",
    ]


def _fulltext_index_lines(ot: ObjectType) -> list[str]:
    if not ot.text_search_fields:
        return []
    label = object_id_to_label(ot.id)
    name = object_id_to_fulltext_index_name(ot.id)
    fields = ", ".join(f"n.{f}" for f in ot.text_search_fields)
    return [
        f"CREATE FULLTEXT INDEX {name} IF NOT EXISTS",
        f"FOR (n:{label}) ON EACH [{fields}];",
    ]


def _meta_lines(ont: Ontology) -> list[str]:
    m = ont.meta
    return [
        "MERGE (m:Meta {id: 'schema'}) SET",
        f"  m.schema_version = {m.schema_version},",
        f"  m.embedding_model = '{m.embedding_model}',",
        f"  m.embedding_dim = {m.embedding_dim};",
    ]


def generate_init_cypher() -> str:
    """Return the full init.cypher text. Pure function — no I/O."""
    ont = load_ontology()
    lines: list[str] = [
        "// Generated by cookbooks/_shared/ontology/gen_init_cypher.py",
        "// DO NOT EDIT BY HAND — run `uv run python -m cookbooks._shared.ontology.gen_all`",
        "",
        "// --- Uniqueness constraints ---",
    ]
    for ot in ont.object_types:
        lines.append(_constraint_line(ot))

    lines.extend(["", "// --- Vector indexes ---"])
    for ot in ont.object_types:
        vlines = _vector_index_lines(ot, ont.meta.embedding_dim)
        if vlines:
            lines.extend(vlines)
            lines.append("")

    lines.extend(["// --- Full-text indexes ---"])
    for ot in ont.object_types:
        flines = _fulltext_index_lines(ot)
        if flines:
            lines.extend(flines)
            lines.append("")

    lines.extend(["// --- Schema meta singleton ---"])
    lines.extend(_meta_lines(ont))
    lines.append("")  # trailing newline
    return "\n".join(lines)


def write_init_cypher(path: Path = OUTPUT_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_init_cypher(), encoding="utf-8")


def main() -> None:
    write_init_cypher()
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
