"""Generates `cookbooks/_shared/skills/_generated_schema.md`.

This is the SCHEMA block the agent reads at planning time. It lists
ObjectTypes (with their canonical id_template), relationships (in the
Cypher `(Source)-[:REL]->(Target)` shape), and ActionTypes (so the
agent knows what affordances exist beyond reading).

The output is intentionally compact — it ships in every agent prompt,
so cost matters. We omit descriptions where the id is self-explanatory.
"""
from __future__ import annotations

from pathlib import Path

from cookbooks._shared.ontology._naming import link_id_to_cypher_rel
from cookbooks._shared.ontology.loader import load_ontology

# parents[3]: cookbooks/_shared/ontology/gen_schema_prompt.py → repo root.
# Output lives at cookbooks/_shared/skills/_generated_schema.md.
OUTPUT_PATH = (
    Path(__file__).resolve().parents[3]
    / "cookbooks" / "_shared" / "skills" / "_generated_schema.md"
)


def generate_schema_prompt() -> str:
    ont = load_ontology()

    lines: list[str] = [
        "<!-- Generated by cookbooks/_shared/ontology/gen_schema_prompt.py -->",
        "<!-- DO NOT EDIT BY HAND — run `uv run python -m cookbooks._shared.ontology.gen_all` -->",
        "",
        "## SCHEMA",
        "",
        "ObjectTypes (Neo4j labels) and their canonical ID shapes:",
        "",
    ]
    for ot in ont.object_types:
        lines.append(f"- **{ot.id}** — `{ot.id_template}`")

    lines.extend(["", "## RELATIONSHIPS", ""])
    lines.append("Use the Cypher form `(Source)-[:REL]->(Target)`. Allowed:")
    lines.append("")
    for lt in ont.link_types:
        rel = link_id_to_cypher_rel(lt.id)
        froms = "|".join(lt.from_types)
        tos = "|".join(lt.to_types)
        lines.append(f"- `({froms})-[:{rel}]->({tos})`")

    lines.extend(["", "## ACTIONS", ""])
    lines.append("Beyond reads, these actions are available (each writes a Decision):")
    lines.append("")
    for at in ont.action_types:
        scopes = f" — scopes: {', '.join(at.scopes)}" if at.scopes else ""
        desc = f" — {at.description}" if at.description else ""
        lines.append(f"- **{at.id}**{desc}{scopes}")

    lines.append("")  # trailing newline
    return "\n".join(lines)


def write_schema_prompt(path: Path = OUTPUT_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_schema_prompt(), encoding="utf-8")


def main() -> None:
    write_schema_prompt()
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
